// <auto-generated />
using DSSD_2022_TP3;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSSD_2022_TP3.Migrations
{
    [DbContext(typeof(AcademicaContext))]
    [Migration("20221007204929_UsuarioTipoUsuario")]
    partial class UsuarioTipoUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DSSD_2022_TP3.Model.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCarrera");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("IdCarrera");

                    b.ToTable("carreras");
                });

            modelBuilder.Entity("DSSD_2022_TP3.Model.Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMateria");

                    b.Property<int>("AnioCarrera")
                        .HasColumnType("int")
                        .HasColumnName("anioCarrera");

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int")
                        .HasColumnName("idCarrera");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("IdMateria");

                    b.HasIndex("IdCarrera");

                    b.ToTable("materias");
                });

            modelBuilder.Entity("DSSD_2022_TP3.Model.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTipoUsuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("tipos_de_usuario");
                });

            modelBuilder.Entity("DSSD_2022_TP3.Model.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTurno");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("IdTurno");

                    b.ToTable("turnos");
                });

            modelBuilder.Entity("DSSD_2022_TP3.Model.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("apellido");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("celular");

                    b.Property<string>("Clave")
                        .HasColumnType("longtext")
                        .HasColumnName("clave");

                    b.Property<string>("Correo")
                        .HasColumnType("longtext")
                        .HasColumnName("correo");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dni");

                    b.Property<bool>("ForzarClave")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("forzarClave");

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int")
                        .HasColumnName("idCarrera");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idTipoUsuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<string>("Username")
                        .HasColumnType("longtext")
                        .HasColumnName("usuario");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdCarrera");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("DSSD_2022_TP3.Model.Materia", b =>
                {
                    b.HasOne("DSSD_2022_TP3.Model.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("IdCarrera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("DSSD_2022_TP3.Model.Usuario", b =>
                {
                    b.HasOne("DSSD_2022_TP3.Model.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("IdCarrera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DSSD_2022_TP3.Model.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("IdTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("TipoUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
